### ISSUE TITLE
config _options[db] 

### ISSUE THREAD

**Issue by seanandmengjia** [TossShinHwa/node-odata#11]
直接配置数据库不可用。
如果不调用set方法，则无法连接db，因为没有调用mongoose.connect(value)
see config.coffee.

**Comment by TossShinHwa** [comment]
是的, 需要执行 `set(db, 'xxx')`, 因为考虑到以后可能要在这里进行一些扩展, 因为期望支持其他数据库类型, 所以没有在这里暴露 mongo 相关的东西, 所以这样设计的.

您的建议是?
