### ISSUE TITLE
$filter 不支持中文的key？

### ISSUE THREAD

**Issue by airyland** [TossShinHwa/node-odata#12]
![image](https://cloud.githubusercontent.com/assets/559179/6103694/cdabd3ae-b081-11e4-918b-569d5a5f77e0.png)

**Comment by TossShinHwa** [comment]
如果是字符串类型,  value 需要使用单引号包裹. 具体规则请参考[这里](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398301).

**Comment by airyland** [comment]
谢谢。没有仔细看文档。
