### ISSUE TITLE
this project looked great until... coffeescript

### ISSUE THREAD

**Issue by tjwebb** [TossShinHwa/node-odata#13]
> node-odata is currently at an alpha stage, it is stable but not 100% feature complete. node-odata is written by CoffeeScript then compiled to Javascript.

> **node-odata is written by CoffeeScript then compiled to Javascript.**

> ## CoffeeScript

why :(

**Comment by TossShinHwa** [comment]
@tjwebb , why not?   :)

**Comment by tjwebb** [comment]
All the modules you use are Javascript. All the code I'm writing is Javascript. So if I wanted to fork and extend this module there'd be this layer in the middle that is twice as hard to debug because the stack trace is impossible to read since it maps to generated code with variables and functions with crazy names.

**Comment by tjwebb** [comment]
Basically: http://tjholowaychuk.tumblr.com.

**Comment by TossShinHwa** [comment]
@tjwebb, you are right. CoffeeScript is real harder to debug than JavaScript. But it still to improve that. At web dev, chrome already support to debug CoffeeScript direct, it's un-necessary to compiled. NodeJS will be soon, I guess.

Other side, I know TJ hate CoffeeScript very much, he have many reason and he is right. But there are many projects still use CoffeeScript, for example: github's [ATOM](https://github.com/atom).

I will think about it what CoffeeScript is applicable to build npm module.

**Comment by TossShinHwa** [comment]
Hi, @tjwebb I am pleased to inform you, this project has been converted to ECMA6, then compiled to ECMAScript 5 by babel :)
