### ISSUE TITLE
更新 node 和 npm 的版本号

### ISSUE THREAD

**Issue by dd1994** [TossShinHwa/node-odata#15]
package.json 里写的是 "node": "0.10.x",  "npm": "1.4.x"，会不会太老了点？

**Comment by TossShinHwa** [comment]
是的. 实际上下一个版本 v0.5.0 需要使用 node v0.12.x . 因为进行了一些重构. 使用了 ES6 的语法.

发布新版本时我会进行更新.

感谢.

**Comment by dd1994** [comment]
非常感谢，试了一下这个东西非常简单易用，看来这次面试有希望了 :sunglasses:
