### ISSUE TITLE
CROS 的问题

### ISSUE THREAD

**Issue by dd1994** [TossShinHwa/node-odata#16]
您好，最近我在使用你的 node-odata 提供 API，ember.js 做前端，碰到了 cros 的问题，
于是我上 SO 提了一个问题：http://stackoverflow.com/questions/30147362/access-control-allow-origin-error-when-using-ember-jswith-ember-cli

回答者说不是 ember 的问题，需要在 服务器端 3000 端口激活 CORS，并给出了链接 http://enable-cors.org/server_expressjs.html

对于 express 我不是很熟，请问在使用 node-odata 的时候如何激活这个 CORS 呢？ 

非常感谢！

**Comment by dd1994** [comment]
非常感谢，我修改了下 node-data/lib/index.coffee 的源码：
```coffee
  app.use (req, res, next) ->
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    res.removeHeader("X-Powered-By")
    next()
```

就这样搞定了。。。虽然我什么也不懂。请问为什么不默认就这样呢？

**Comment by TossShinHwa** [comment]
你这样是可以的, 但是更正确的做法参考 [这里](https://github.com/TossShinHwa/CMS/blob/master/server/server.coffee#L21), 直接使用一个中间件即可.

CORS 是一套规范, 有很多参数 (比如只允许某些 host 访问, headers 只允许指定的 key 等). 如果直接集成了又有人会问, 怎么直接就能 CORS 了.

**Comment by dd1994** [comment]
非常感谢 @TossShinHwa
