### ISSUE TITLE
请问如何实现下一页的功能？

### ISSUE THREAD

**Issue by dd1994** [TossShinHwa/node-odata#17]
比如直接 get `/books` 会得到所有的 books，但是有时候如果 book 太多的话（比如有几万本）一个 json
明显太大了，可以直接通过 `$top=10` 返回前 10 本书。但是我想不通过这个 `top` 查询，而是直接类似
这样 http://services.odata.org/V2/Northwind/Northwind.svc/Customers?%24format=JSON 有一个  "__next" 属性，这样就可以得到下面 20 个人的信息了，主要是比较方便前端处理。请问这样的 "__next" 功能如何通过 node-odata 实现呢？

**Comment by TossShinHwa** [comment]
这是 OData 规范中的 metadata 的一种. metadata 在规范中并不是强制要求实现.

一般来说使用 top + skip 即可实现分页, 并且控制更灵活. 如果使用 next, 无法控制 pageSize 的大小.

假设你分页是每页10条, 想要第二页的内容. 使用 `$top=10&$skip=10` 即可.

具体代码可以参考[这里](https://github.com/TossShinHwa/CMS/blob/master/client/public/app/article/list/article-list.coffee#L15-L16)

**Comment by dd1994** [comment]
thank you @TossShinHwa

**Comment by dd1994** [comment]
想了一下确实觉得用 top 和 skip 比较合理。
