### ISSUE TITLE
Should allow use PATCH to update resource.

### ISSUE THREAD

**Issue by TossShinHwa** [TossShinHwa/node-odata#19]

**Comment by 503945930** [comment]
patch.js


"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

exports["default"] = function (req, MongooseModel) {
    return new Promise(function (resolve, reject) {
        if (!Object.keys(req.body).length) {
            return reject({ status: 422 });
        }
        MongooseModel.findOneAndUpdate({ _id: req.params.id },req.body,{"new":true},function(err,entity){
            if (err) {
                return reject(err);
            }
            return resolve({ status: 201, entity: entity });
        });
    });
};

module.exports = exports["default"];







使用方法：

<script>


    //更新子文档
    $(function(){
        var f=$.ajax({
            url:"http://127.0.0.1:3000/activities(dc7f134c-1f93-454a-970f-cb962dc2bf84)",
            type:"patch",
            data:{"creatInfo.perple":"eeeee","updateInfo.perple":"weiyang"}
        });
        f.then(function(result){
            console.log(result);
        },function(err){
            console.log(err);
        })

    });
/*// 更新子数组
    $(function(){
        var f=$.ajax({
            url:"http://127.0.0.1:3000/activities(dc7f134c-1f93-454a-970f-cb962dc2bf84)",
            type:"patch",
            data:{"images.poster.0":"wwww.vaid.com"}
        });
        f.then(function(result){
            console.log(result);
        },function(err){
            console.log(err);
        })

    })*/
</script>

**Comment by 503945930** [comment]
使用方法：

<script>


    //更新子文档
    $(function(){
        var f=$.ajax({
            url:"http://127.0.0.1:3000/activities(dc7f134c-1f93-454a-970f-cb962dc2bf84)",
            type:"patch",
            data:{"creatInfo.perple":"eeeee","updateInfo.perple":"weiyang"}
        });
        f.then(function(result){
            console.log(result);
        },function(err){
            console.log(err);
        })

    });
/*// 更新子数组
    $(function(){
        var f=$.ajax({
            url:"http://127.0.0.1:3000/activities(dc7f134c-1f93-454a-970f-cb962dc2bf84)",
            type:"patch",
            data:{"images.poster.0":"wwww.vaid.com"}
        });
        f.then(function(result){
            console.log(result);
        },function(err){
            console.log(err);
        })

    })*/
</script>
