### ISSUE TITLE
Why using books/:id instead of books(:id)/?

### ISSUE THREAD

**Issue by janhommes** [TossShinHwa/node-odata#2]
Hi there,

first: Thank you for this great project. It looks promising.

But why are you using the `books/:id` url route instead the defined Odata way `books(:id)`? I also don't like this syntax that much, but it is set as the standard and your server should support it. Or what do you think?

greetings
Jan

**Comment by dcs619** [comment]
+1 for removing Express dependencies.  We'd use this library in a Meteor app so any extra web framework is unnecessary.

**Comment by TossShinHwa** [comment]
@dcs619 cool, a Meteor app.

Express now been included in the internal dependencies, the external can not directly accessible. You don't need to install it now.

Express dependencies will be completely removed sometime in the future.

**Comment by TossShinHwa** [comment]
Fixed, add param `enableOdataSyntax `, https://github.com/TossShinHwa/node-odata/commit/632e939789a69524102414b9ad6e0b0fa53abb7d

**Comment by TossShinHwa** [comment]
Changed to standard format.
