### ISSUE TITLE
suggestion: add mongooseModel parameter on resources.register

### ISSUE THREAD

**Issue by the-AjK** [TossShinHwa/node-odata#26]
Hi, 
It would be useful to be able set a different mongooseModel when registering a new resource rather than use the url parameter as the name of the mongoDB collection:

```js
server.resources.register({
    url: '/libri',
    mongooseModel: '/books',
    model: {
        title: String,
        price: Number
    }
});
```

**Comment by TossShinHwa** [comment]
Actually, the url param will ignore '/' char if your url contain it. So, if you want to mongooseModel is 'books', you can set url is '/books' or 'books'. it's the same.

I think keep url and resource name is a better way to practice, and I will let this module support more other DB. So, add `mongooseModel` param maybe isn't a good choose.

Thank you for your suggestion.

**Comment by the-AjK** [comment]
good choose to support more other DB, my point was to be able to set the url with a different string rather than use the resource name.

**Comment by TossShinHwa** [comment]
Right, maybe should add this optional param. Sometime, the resource name will different from url.
