### ISSUE TITLE
关于 cors 中间件的正确使用姿势

### ISSUE THREAD

**Issue by dd1994** [TossShinHwa/node-odata#27]
嗯目前我是直接改 `node_modules/node-odata/lib/index.coffee` 里的内容的，我把这个文件里面直接加上
```
cors = require('cors')
// ...此处省略一大段
app.use(cors())
```

虽然这样就能用了，但是当然我知道直接改这样不太好的。。

我在我的 index.js 尝试这样改:

```
 var cors = require('cors');
var odata = require('node-odata');

var server = odata('mongodb://localhost/odata_ember');

server.resources.register({
  url: '/articles',
  model: {
    title: String,
    content: String,
    category: String
  }
});

server.use(cors());
server.listen(3000);
```

当然这样是不行的，请问具体改怎样做呢？谢谢！

**Comment by TossShinHwa** [comment]
Hi @dd1994,

在新的版本 (v0.6.0) 中已经默认启用了 cors, 详见 #16.

你这写法不能支持的原因是 `server.use(cors())` 需要在 `server.resources.register(...)` 之前调用才行. 否则无法生效. (其实这是一个 bug)

所以, 你有2种方式解决这个问题:

1. 交换一下代码的顺序
2. 更新一下版本到 0.6.0

谢谢.

**Comment by dd1994** [comment]
真的换下顺序就好了，非常感谢，已经能用了。
