### ISSUE TITLE
the function named `before` of resource will not be execute

### ISSUE THREAD

**Issue by bici-guangyuan** [TossShinHwa/node-odata#31]
我要在post方法执行前后记录日志信息，按照api文档中关于before，after的用法，发现before方法没有被执行，请问如何实现。

**Comment by TossShinHwa** [comment]
是的, 这是我之前挖的一个坑 T_T

做的时候就知道可能有 bug, 不过当时由于没有使用 `before` 这个 api, 所以就没有去测试它.

0.7 版中将解决这个问题. (预计本周完成) 目前请暂时使用 after. 

另外, 设计 `before` 主要是为了进行一些验证, 如果不符合规则等, 在最后 `return false` 将阻止相应的操作执行. `after` 主要是为了可能在插入数据之后还有一些后续操作. 比如要重新计算其他 `resource` 的某个字段, 或可能要做一些 log. 因为 `before` 会阻塞整个请求, 所以建议如果只是记录 log 的话在 `after` 中进行, 因为它是异步的, 当 REST 的操作完成后将直接返回给客户端, 剩下的操作将在返回后执行.

这一点没有在文档中进行说明, 表示抱歉. 之后我会添加到文档中.

感谢关注.

**Comment by TossShinHwa** [comment]
Fixed it on https://github.com/TossShinHwa/node-odata/commit/969ab5da0054eedb90f25935a6dd2baa9ec993fa.

**Comment by bici-guangyuan** [comment]
我的实际意图是要记录 每次操作的服务器处理耗时。
设计在before中放入开始时间，在after中用（当前时间－开始时间）计算出方法的总耗时，是否可行？
或者有其他更好的记录方式吗

**Comment by TossShinHwa** [comment]
可以考虑使用 [response-time](https://github.com/expressjs/response-time) 中间件.

**Comment by bici-guangyuan** [comment]
谢谢，已经搞定
