### ISSUE TITLE
before(req)

### ISSUE THREAD

**Issue by bici-guangyuan** [TossShinHwa/node-odata#36]
// 配置 POST /resource
.post().before(req)方法会执行2次before方法

**Comment by TossShinHwa** [comment]
在 v0.7.4 中已解决了这个问题. 请问您的版本是?

**Comment by bici-guangyuan** [comment]
0.7.4
调用时，第一次req有值，第二次req为null

**Comment by TossShinHwa** [comment]
[这里] (https://github.com/TossShinHwa/node-odata/blob/0.8/test/hook/hook.post.before.coffee#L16-L32) 有一个 test case, 运行起来是没有问题的.

请问您具体是怎么申明的呢?

**Comment by bici-guangyuan** [comment]
server.post()
.auth(function (req) {
	return true;})
.before(function (req) {
	console.log(req,i);
})

**Comment by TossShinHwa** [comment]
测试了一下, 确实存在这个问题. 稍后我看看.

```
var odata = require('node-odata');

var server = odata('mongodb://localhost/my-test');

server.resource('books', {
  title: String,
  price: Number
})
.post()
.before(function (entity) {
  console.log(entity);
});

server.listen(3000);
```

**Comment by TossShinHwa** [comment]
Sorry, 在最新的代码已经修复了, 只是还没来得及发布就被你发现了这个 bug. ([https://github.com/TossShinHwa/node-odata/commit/6da49ff48123ee45453053397317519deac87c2d#diff-4c3ff43065a6a6b0fa3b753ae24cdda2R64](https://github.com/TossShinHwa/node-odata/commit/6da49ff48123ee45453053397317519deac87c2d#diff-4c3ff43065a6a6b0fa3b753ae24cdda2R64))

现在已发布了 v0.7.5 修复这个问题, 感谢反馈.
