### ISSUE TITLE
put before method

### ISSUE THREAD

**Issue by bici-guangyuan** [TossShinHwa/node-odata#37]
put().before(function(entity){
   entity.name='test';
})
执行后数据库中的name没有变化

version：0.7.4

**Comment by TossShinHwa** [comment]
可能确实有这个问题, 那部分的代码比较 ugly, 稍后我会修复这个问题, 顺便重构下 :)

感谢反馈.

**Comment by SlavePaul** [comment]
Aloha

**Comment by TossShinHwa** [comment]
Fixed on v0.7.6
