### ISSUE TITLE
Status of this repo ?

### ISSUE THREAD

**Issue by agjs** [TossShinHwa/node-odata#39]
Are you guys still working on this ? What about future updates and some production ready version ?

**Comment by TossShinHwa** [comment]
Hi agjs,

Yes, it's still in the update. You can use it in a production environment already, but some APIs maybe will be change in future versions. Next version's major work is add $metadata. ([#25](https://github.com/TossShinHwa/node-odata/issues/25))

**Comment by nursultan156** [comment]
Hi,

I implemented one of the examples and trying to get data via Excel 2013 using "From ODATA web chanel", and getting error, can anyone explain why Excel cannot get data from ODATA channel?
Whereas from browser it is ok.

**Comment by TossShinHwa** [comment]
@nursultan156, Sorry about that, it's not work because [$metadata is missing](https://github.com/TossShinHwa/node-odata/issues/25), and we are working for implement it.
