### ISSUE TITLE
GET/books(:id)为什么不能用了？

### ISSUE THREAD

**Issue by fungwan** [TossShinHwa/node-odata#44]
作者你好，我用这个API查找对应ID的资源怎么总是返回404呢？我确定数据库里面有对应资源。不同的ID值查询总是返回相同的结果，DELETE以ID值为查询也是404

**Comment by TossShinHwa** [comment]
可以的吧, url 中是没有引号的.

[http://books.zackyang.com/book(6c737509-a431-4b06-ba01-e7cb253b6fad)](http://books.zackyang.com/book(6c737509-a431-4b06-ba01-e7cb253b6fad))

**Comment by fungwan** [comment]
对的，我是没有用引号。不过现在可以了。之前的id号是以mongodb默认的objectID值查询的，ObjectId("5655697ac5cf723f0b7939c9")，/books(5655697ac5cf723f0b7939c9),就不行，但是换成作者你的uuid的这种格式就可以了。请问这个跟格式有关吗？

**Comment by TossShinHwa** [comment]
用 ObjectId 理论上来说应该是没问题的. 只要能通过下面这行代码查询出来就可以了.

[https://github.com/TossShinHwa/node-odata/blob/master/src/rest/get.js#L5](https://github.com/TossShinHwa/node-odata/blob/master/src/rest/get.js#L5)

有具体的 demo 吗?

**Comment by fungwan** [comment]
作者你好，我之前断点调试到你链接给出的地方，返回还是404。我就是用的你官网的例子运行的，数据文件也都是你test/support里面的books.json，但是GEt (ObjectId)类型就不行。楼主有时间的话可以试试看看呢。

**Comment by TossShinHwa** [comment]
Hi @fungwan, 是[这个](https://github.com/TossShinHwa/node-odata/blob/master/examples/simple-with-data/index.js)例子吗? 但是我例子中默认插入的数据应该是 uuid 的格式呢. 意思是你用的原来的数据? 这个我需要测试一下才知道原因.

**Comment by fungwan** [comment]
你好，我没有按照你的例子进行插入数据，而是我自己手动将数据通过mogouve可视化工具导入到mongodb的，所以生成的格式不是uuid，而是 ObjectId，所以再用你的GET/books(:id)这个API查询就不成功。

**Comment by TossShinHwa** [comment]
好的, 稍后我试试.

**Comment by fungwan** [comment]
作者你好，怎么样，确认重现了没？

**Comment by TossShinHwa** [comment]
是的, 确实有这个问题. 大概是因为 mongoose 查询时, 如果是 ObjectId, 需要做一个转换才行, 不能直接用字符串来查 ObjectId.

建议直接用该服务提供的 API 来插入数据.

**Comment by fungwan** [comment]
感谢回复。作者你的意思是现有的该服务不能满足以ObjectId的方式进行查询哇？主要是我这边mongodb里面的数据是其他服务程序插入进去的，其id类型就是默认的ObjectId。另外你提到的转换是指怎样的操作呢？

**Comment by TossShinHwa** [comment]
Hi, @fungwan 

因为使用 node-odata 默认的 id 类型为 uuid, 如果你要使用 ObjectId 作为 id 类型的话, 需要进行显示声明. 

示例如下:

```javascript
var bookInfo = {
  _id: require('mongoose').Schema.ObjectId,  // <------ 显示声明为 ObjectId
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};
```

**Comment by fungwan** [comment]
好的，谢谢作者。抽空试试。

**Comment by netssfy** [comment]
显示声明_id可以解决get的问题
但是$filter=belongTo%20eq%2056775b9abf29cde453327f98
其中belongTo这个field是一个ObjectId类型，HTTP返回500， 结果为
Syntax error at '56775b9abf29cde453327f98'.

**Comment by TossShinHwa** [comment]
@netssfy, 是的, 会有这个问题. 但是一般 id 都直接 /resource(:id) 直接查询吧. 很少会用 $filter 的情况.

稍后我会修复这个问题.

谢谢.

**Comment by TossShinHwa** [comment]
Fixed on `v0.7.13`.
