### ISSUE TITLE
POST操作，有错误发生时，HTTP的RESPONSE返回200和OK

### ISSUE THREAD

**Issue by netssfy** [TossShinHwa/node-odata#45]
POST操作，如果MONGODB抛出了错误，比如DUPLICATED KEY。
可以看到MONGO报错了
![2](https://cloud.githubusercontent.com/assets/6095138/12423618/44e5073a-bf07-11e5-8518-5ecd297cd454.png)
但是到errorPipe里，result是直接来自mongoose的error对象，而非node-odata在errorPipe里所期望的result
![1](https://cloud.githubusercontent.com/assets/6095138/12423584/225b901c-bf07-11e5-9401-eff216b2e222.png)

**Comment by TossShinHwa** [comment]
Fixed at `v0.7.7`, 修改为: 若 mongodDB 内部错误, 将直接返回 500 与相应的 message.
