### ISSUE TITLE
Cannot find module './Resource'

### ISSUE THREAD

**Issue by baishiup** [TossShinHwa/node-odata#46]
在阿里云服务器上安装node-odata模块时，报错
module.js:341
    throw err;
    ^

Error: Cannot find module './Resource'
在这个环境下测试了express，运行没有问题

**Comment by baishiup** [comment]
module.js:341
    throw err;
    ^

Error: Cannot find module './Resource'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/nodejs/yk_user/node_modules/node-odata/lib/server.js:47:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/nodejs/yk_user/node_modules/node-odata/lib/index.js:13:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by TossShinHwa** [comment]
'v0.7.7' 应该解决了这个问题，请问您安装的版本号是？

**Comment by baishiup** [comment]
版本号是node-odata@0.7.7
我其实我在本地使用node-odata是可以得没有问题，在阿里云服务器上就出现了Error: Cannot find module './Resource'

> kerberos@0.0.18 install /opt/nodejs/test/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/opt/nodejs/test/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/opt/nodejs/test/node_modules/kerberos/build'
这个是安装模块时的提示，请问是我的环境有问题吗？

**Comment by TossShinHwa** [comment]
请问 'node' 合 'npm' 的版本呢？ （不建议使用 'npm v3'）

这个 bug 在之前的一次 [commit](https://github.com/TossShinHwa/node-odata/commit/b3bd05465d9de6ad7130d97ec1229179f9204464) 中已经解决了， 你可以看看在 node_modules/node-odata/lib/ 下的 'Resource.js' 文件 R 是否为大写.

如果是 0.7.7 应该是大写才对 :)

**Comment by baishiup** [comment]
不对不对  我看了我在本地和一个已经上线的项目 resource.js都是小写的！还有function.js index.js server.js  都是小写的

**Comment by baishiup** [comment]
nodeh和npm的版本都是v5.5.0和3.3.12

**Comment by baishiup** [comment]
我尝试了吧这4个文件都改成首字母大写的 则报错找不到lib

**Comment by TossShinHwa** [comment]
建议先安装node 4.x.x 试试，我没有在5.x下面测试过。并且现在配套的 npm v3 也非常蛋疼。

等我有网络的时候我再测试下 5.x 的问题吧。

**Comment by baishiup** [comment]
谢谢 那我先换成4X的试试

**Comment by baishiup** [comment]
node版本 4.2.6 npm版本2.14.12  依然是同样的错误

**Comment by baishiup** [comment]
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/opt/nodejs/test/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nodejs/test/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by TossShinHwa** [comment]
这个看起来是mongoDB的错呢，你正确安装了mongoDB吗？

**Comment by baishiup** [comment]
**安装mongodb**

# wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian71-3.2.1.tgz
wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-3.2.1.tgz

# tar zxf mongodb-linux-x86_64-debian71-3.2.1.tgz

重命名
# mv mongodb-linux-x86_64-debian71-3.2.1 mongodb

移动
# mv mongodb /opt/mongodb

创建数据库
# mkdir /opt/mongodb-db

创建logs
# mkdir /opt/mongodb/logs
# touch /opt/mongodb/logs/mongodb.logs

设置开机启动
# nano /etc/rc.local


这是我安装mongodb的步骤 访问端口27017是正常的啊

**Comment by baishiup** [comment]
我试着安装mongoose 并没有报错

**Comment by baishiup** [comment]
你好 现在是这样的 我把测试文件放在刚安装的node-odata  会报错  ，
然后我把测试文件放到现在线上的项目里面不会报错了，我想应该是模块本身的问题吧，希望有时间你看一下~

**Comment by baishiup** [comment]
我现在使用v0.7.6就可以了  0.7.7有问题！

**Comment by TossShinHwa** [comment]
请问测试文件是？

**Comment by baishiup** [comment]
var odata = require('node-odata');
var server = odata('mongodb://localhost/test');
server.resource('user', {
	username: String, //用户名
	password: String, //密码
	name: String, //姓名
	idcard: String, //身份证
	level: {
		type: Number,
		default: 0
	}, //会员等级
	score: {
		type: Number,
		default: 0
	}, //积分
	balance: {
		type: Number,
		default: 0
	}, //余额
	inputtime: Date //注册时间
});
server.listen(10100,function(){
	console.log("listen 5000");
})

**Comment by TossShinHwa** [comment]
`0.7.7` 测试没有问题.

**Comment by baishiup** [comment]
debian还是一样报错  win10没有问题，不过win10好像一直都可以

**Comment by TossShinHwa** [comment]
你使用的是 `npm` 官方源吗?

**Comment by baishiup** [comment]
是的  淘宝源也试过

**Comment by TossShinHwa** [comment]
我在 `Ubuntu` 和 `centos` 上运行都是没有问题的, 可能是您的环境问题. 麻烦再检查下. 因为之前是从 v5 降下来的, 可能会有蛋疼问题.

**Comment by baishiup** [comment]
哦哦  不好意思我技术有限，只能从我碰到的几个方面来测试：）   我这里3个不同的debian版本 全部都报错  nodejs分别是4.3.0   5.5.0 ， debian是8.2和7.9，7.8。 所有文件报错的lib文件夹下的js文件都是首字母小写的  然后win10不报错，估摸着是不是win10不区分大小写？

**Comment by baishiup** [comment]
我现在都换成0.7.6是正常的，或许是0.7.7在debian上的兼容？

**Comment by TossShinHwa** [comment]
```
gyp ERR! cwd /opt/nodejs/test/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
```

根据前面的报错, 你可以尝试重新安装一下 kerberos, 再 `npm install` 看看还会不会报错.

```shell
apt-get install libkrb5-dev
```

另外, 建议 `install` 之前再清空一下缓存.

```shell
npm cache clean
```

**Comment by TossShinHwa** [comment]
已修复这个问题, 修复于 `v0.7.8`.

这大概是因为我修改了文件名大小写, 但是没有再发布, 所以我运行代码都是正常的, 但是从 npm 安装的话就会报错.

Sorry, 请安装新版本后再试一下.

**Comment by rodri042** [comment]
This was fixed in `v0.7.8` (https://github.com/TossShinHwa/node-odata/pull/47)

**Comment by baishiup** [comment]
@TossShinHwa 好的~

**Comment by baishiup** [comment]
@rodri042 thanks
