### ISSUE TITLE
reference to another document

### ISSUE THREAD

**Issue by tomerpar133** [TossShinHwa/node-odata#48]
hi

how can I reference the resource to another resource?
(reference document to another)

for example: 
server.resource('books', {
title: String,
price: Number
});

server.resource('authors', {
name: String,
books: [ ~reference to book~ ]
});

I noticed that the _id is generated by type string and every time I use {type: String, ref: 'books'} the inserted data is {name: "foo", books: ["[object Object]"]}

is there a way to use reference?

thanks

**Comment by TossShinHwa** [comment]
Hi @tomerpar133 ,

When you use mongoDB which is NoSQL database for persistent data, the best practices is that define a complex type to do this.

In your example, you should:

```
server.resource('books', {
title: String,
price: Number
authors: {
  name: String
},
categories: [{
  name: String
}],
...
});
```

So, you maybe not necessary to use `reference`.

**Comment by tomerpar133** [comment]
Hi

I need to do other manipulations on authers and I need it in another document 

Is therea way to reference a collection to another?

**Comment by TossShinHwa** [comment]
Hi,

Unfortunately, it's not support `reference`, at least for now. You have to query again, which you want to reference's resource (The worst case you should query `N+1` times).

You can save resource's id in another resource. For example:

```js
server.resource('books', {
  title: String,
  price: Number
});

server.resource('authors', {
  name: String,
  books: [{ String }]  // <--- book's id
});
```

Once again, good way is that define a complex type, even need redundant data.

GOOD: easy to query, and faster.
BAD: need update multiple resources when you want to modify it.

```js
server.resource('books', {
  title: String,
  price: Number,
  author: {
    name: String
  }
});

server.resource('authors', {
  name: String,
  books: [{
    title: String,
    price: Number
  }]
});
```

**Comment by tomerpar133** [comment]
Ok
Thank you

**Comment by bastianbin** [comment]
Hi, is there any work invested into enabling this? Especially with complex data with lots of data this would be helpful since data modeling does reduce the size of the db. I understand the workaround but using the reference might make it easier to automatically generate code to consume the api.
