### ISSUE TITLE
The internal ID _id is not returned

### ISSUE THREAD

**Issue by mauriceKA** [TossShinHwa/node-odata#53]
When I query for objects, the internal ID of the MongoDB document is not returned.

```
Request: http://localhost:3000/subscriptionConfigurations
Response-Body: 
{
  "value": [
    {
      "id": "2016-04-28T13:19:09.907Z",
      "text": "foo bar 32"
    }
  ]
}
```
However: in the DB, the object has the internal id _id : d30b54e9-12a2-49ba-8da0-87b3c1500aab

I can also request it directly:
```
Request: http://localhost:3000/subscriptionConfigurations(d30b54e9-12a2-49ba-8da0-87b3c1500aab)
Response: 
{
  "id": "2016-04-28T13:19:09.907Z",
  "text": "foo bar 32"
}
```

In my server code, I use:
```
server.resource('subscriptionConfigurations', { 
	_id: String,
	id: Date, 
	text: String 
});
```

Why is _id not returned?

When I try in the server code
```
server.resource('subscriptionConfigurations', { 
	_id: require('mongoose').Schema.ObjectId,
	id: Date, 
	text: String 
});
```
... I get this error message:
`Cast to ObjectId failed for value "d30b54e9-12a2-49ba-8da0-87b3c1500aab" at path "_id"`

I'm using MongoDB version 3.0.11

**Comment by mauriceKA** [comment]
Strangely, when I remove the id field ...
```
server.resource('subscriptionConfigurations', { 
	//	_id: String,
	//id: Date, 
	text: String 
});
```
... I get the internal ID, but not as _id as expected, but as id:
```
{
  "id": "d30b54e9-12a2-49ba-8da0-87b3c1500aab",
  "text": "foo bar 32"
}
```
Is this by intention?

**Comment by TossShinHwa** [comment]
You can't use `id` as a key to save yourself data, because it's a INTERNAL field in `node-odata`, and it mapping to mongoDB's `_id` field.

This is designed to isolate mongodb. (because maybe `node-odata` will support others DB)

So, you can change to another filed name, eg:

```
server.resource('subscriptionConfigurations', { 
    date: Date, 
    text: String 
});
```

Then, `id` filed will auto-generate to be a UUID.

**Comment by mauriceKA** [comment]
Thanks for your comment. Then you should update the documentation at
https://tossshinhwa.github.io/node-odata/en/

There, the examples imply, that the property `_id` is returned, while, as you described it above, actually `id` is used.

Nevertheless, thank you for the great tool. Keep up your great work!

**Comment by TossShinHwa** [comment]
Thank you for remind, I will update docs ASAP.

**Comment by TossShinHwa** [comment]
[Documentation](https://tossshinhwa.github.io/node-odata/en/) has been updated.
