### ISSUE TITLE
Live Demo links not working

### ISSUE THREAD

**Issue by mauriceKA** [TossShinHwa/node-odata#54]
The live demo links `http://books.zackyang.com/book` on the README.md are not working. They deliver the following error:

```
502 Bad Gateway
nginx/1.4.6 (Ubuntu)
```

**Comment by TossShinHwa** [comment]
Aha, you catch me. 

Because I update `node-odata` depends on the version of NodeJS (from 0.10 -> 0.12 at leaset). But I'm too lazy to update my server's NodeJS version and I don't want to run the old example. T_T

And now, it fixed. Try it plz.
