### ISSUE TITLE
Update with PUT not working

### ISSUE THREAD

**Issue by mauriceKA** [TossShinHwa/node-odata#55]
I have quite a complex model:

```
server.resource('subscriptionConfigurations', { 
	user: String,
	topics: [{
		name : String,
		situationDescriptions : [{
			criteria : {
				stocks : {
					enabled : Boolean,
					exchange : String,
					stockChangeAmount : Number,
					stockChangeDirection : String,
					stockChangeUnit : String,
					symbol : String
				},
				tweets : {
					enabled : Boolean,
					hashtags : Array,
					keywords : Array,
					operator : String,
					tweetNumber : Number,
					tweetOperator : String,
					users : Array
				},
				periodNumber : Number,
				periodUnit : String
			}
		}]

	}]
});
```

Here, updating a document with PUT fails. The response of the PUT returns exactly what I have put into the request payload, however when I do a get on the document or get all documents, the document that should have been updated is still in the old version.

I only can circumvent this by deleting the document and POSTing it again. Can you please look at it?

**Comment by TossShinHwa** [comment]
I never to try so complex model before, and after I tried, it did have BUG.

I will fix it later, before this, plz try to use a simple model, it will works :)

**Comment by mauriceKA** [comment]
I tried to identify the minimal example. I think I found it:
```
server.resource('test', { 
    p1: [{
        p2: String
    }]
});
```

If I use this and try to update a document in the test collection by adding one more object in the array p1, the update will not be correct.

So it seems that the arrays are a problem. I think this is where the bug is located.
