### ISSUE TITLE
npm can't install this module

### ISSUE THREAD

**Issue by crcren** [TossShinHwa/node-odata#56]

**Comment by crcren** [comment]
why？

**Comment by TossShinHwa** [comment]
node version?
npm version?

Could you paste the error log?

**Comment by crcren** [comment]
> kerberos@0.0.21 install /usr/lib/node_modules/node-odata/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/lib/node_modules/node-odata/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: 没有那个文件或目录
compilation terminated.
kerberos.target.mk:92: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/lib/node_modules/node-odata/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-odata/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> bson-ext@0.1.13 install /usr/lib/node_modules/node-odata/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/lib/node_modules/node-odata/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/usr/lib/node_modules/node-odata/node_modules/bson-ext/build'

**Comment by TossShinHwa** [comment]
Upgrade nodejs > v4.0.0 and try it again plz.

**Comment by crcren** [comment]
The problem remains unresolved

**Comment by crcren** [comment]
> kerberos@0.0.21 install /usr/lib/node_modules/node-odata/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/lib/node_modules/node-odata/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: 没有那个文件或目录
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/lib/node_modules/node-odata/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-odata/node_modules/kerberos
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> bson-ext@0.1.13 install /usr/lib/node_modules/node-odata/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/lib/node_modules/node-odata/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/usr/lib/node_modules/node-odata/node_modules/bson-ext/build'

**Comment by crcren** [comment]
刚刚发现，您是中国人

**Comment by TossShinHwa** [comment]
是的. 你需要安装 `libkrb5-dev`, 可以解决这个问题.

You should install `libkrb5-dev` to resolve this problem.

**Comment by crcren** [comment]
https://registry.npmjs.org/node-pdata
已经找不到该包，被删除了吗？

**Comment by TossShinHwa** [comment]
使用 apt-get 或 yum 安装

**Comment by crcren** [comment]
sudo apt-get install node-pdata ?
没有这个包，是不是要添加第三方源？

**Comment by crcren** [comment]
又可以安装了，装上了

**Comment by crcren** [comment]
发现逻辑运算少了 in 和 nin 功能。以后考虑添加吗？

**Comment by TossShinHwa** [comment]
会加上的 :)

**Comment by crcren** [comment]
刚刚看了odata规范，好像确实没有这个运算符。
那么我很好奇，假如我要查询 id in array（1,2,5,7,8[...]）的记录，如何实现该功能呢？

**Comment by TossShinHwa** [comment]
有一个 [has](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398302), 和 `in` 是相同功能.

**Comment by crcren** [comment]
谢谢

**Comment by crcren** [comment]
谢谢
