### ISSUE TITLE
examples目录里的complex例程如何增删查？

### ISSUE THREAD

**Issue by crcren** [TossShinHwa/node-odata#57]
我post的时候按照schema格式 制作body 如下：
{
  custom: {
    id: "1",
    name: "john"
  },
 orderItems: [{
    quantity: 10,
    product: {
      id: "1",
      name: "com",
      price: 2.1
    }
  }]
}

但是返回错误：
SyntaxError: Unexpected token c<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/home/wxd/node/test-odata/node_modules/body-parser/lib/types/json.js:88:17)<br> &nbsp; &nbsp;at /home/wxd/node/test-odata/node_modules/body-parser/lib/read.js:108:18<br> &nbsp; &nbsp;at invokeCallback (/home/wxd/node/test-odata/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/home/wxd/node/test-odata/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/wxd/node/test-odata/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at emitNone (events.js:67:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)

**Comment by TossShinHwa** [comment]
request data 只接受 JSON 格式的数据, JavaScript object 是不行的, 你可以尝试:

```
POST /orders

{"custom":{"id":"1","name":"john"},"orderItems":[{"quantity":10,"product":{"id":"1","name":"com","price":2.1}}]}
```

**Comment by crcren** [comment]
Thx，it's done.

**Comment by crcren** [comment]
还有一个问题：
 .before(function (entity) {...})  这个before方法里可以对request内容进行更改吗？这样可以不必重定义post等方法？ 怎么做？

**Comment by TossShinHwa** [comment]
可以的.

```
server.resource('orders', order)
.post().before(function (entity) {
    entity.custom.name = "zack";
});
```

**Comment by fungwan** [comment]
@TossShinHwa 你好，如果request data的json数据里面包含了中文，POST会失败。都是英文的话不会返回ERROR。试试下面这段代码呢？看你那边会不会。
```javascript

var http = require('http');

var bookBody = {
    "title": "黑客与画家",
    "price":9.89
}

var bookBodyString = JSON.stringify(bookBody);
var options = {
    host: 'localhost',
    port:'3000',
    path: '/books',
    method: 'POST',
    headers: {
        'Accept': '/',
        'Content-Type':'application/json',
        'Content-Length': bookBodyString.length
    }
};

var req = http.request(options, function(res) {
    res.setEncoding('utf8');
    res.on('data', function(data) {
        console.log(data);
    });

    res.on('err',function(data){
        console.log(data);
    });
});


req.write(bookBodyString);
req.end();`
```

**Comment by TossShinHwa** [comment]
这么取长度是不对的.

```
'Content-Length': bookBodyString.length
```

你可以考虑去掉这个参数, 让他自动计算, 就不会报错了.

**Comment by fungwan** [comment]
谢谢，果然是中文的坑。或者改成下面获取长度也可以避免。
`Buffer.byteLength(bookBodyString, 'utf8')`

**Comment by TossShinHwa** [comment]
Great! 我之前都没有手动去处理过 req 的 length 问题, 学习了.

**Comment by crcren** [comment]
node test.js 
{"title":"黑客与画家","price":9.89,"id":"7f9224d6-3b8c-4a14-9606-b665e17cec7d"}

我刚刚看到，调试的时候也是报错误，后台我对比curl，去掉了 content-length，就ok了
