### ISSUE TITLE
可选配置项auth函数里面不能在异步方法里面返回trueORfalse

### ISSUE THREAD

**Issue by fungwan** [TossShinHwa/node-odata#59]
作者你好，在注册一个resource时，因需求我需要对该资源进行权限验证，那我在auth()里面是有这样的逻辑：获取req.headers里面的token值，然后我会将它传到某个异步方法里面去验证，再根据结果返回trueOrfalse，伪代码像这样：

```javascript
.list()
.auth(function(req){
       
       var token = req.headers.authorization;
       
       VerifyToken(token,function(err,result){
            if(err === null)return true;
            return false;
       })
   })
```
但像这样实做了后发现，无论怎样,服务器返给API请求端的响应都是401。业务逻辑里面我可以保证该token值是有效的，返回的err等于null（本应是有权访问该资源）。那我把异步的验证方法注释掉，直接return true或者false，服务器返回又是正常的。请问这个怎么解决呢？谢谢。

**Comment by TossShinHwa** [comment]
Hi, 您可以参考下[这个中间件](https://github.com/TossShinHwa/CMS/blob/node-and-angular/server/middleware/authorization.coffee)的写法, 然后[在 server 中注册](https://github.com/TossShinHwa/CMS/blob/node-and-angular/server/server.coffee#L18)这个中间件. 这个中间件可以在 req 中加入一个对象, 来表示用户是否登录.

然后在您[需要权限校验的地方](https://github.com/TossShinHwa/CMS/blob/node-and-angular/server/resources/board/board.coffee#L8), 只需要[判断一下这个对象是否存在](https://github.com/TossShinHwa/CMS/blob/node-and-angular/server/resources/auth.coffee#L2), 就可以实现简单的登录功能. 设置你可以在中间件里把详细的权限读取出来, 这样可以做更复杂的权限校验.

不过要注意的是, 这个中间件每个请求都会先执行, 所以如果权限数据的查询比较复杂, 建议使用缓存来提高性能.

**Comment by fungwan** [comment]
OK，谢谢建议。对了，还有一个问题，配置all.auth()时候会程序会抛异常，如下：
```javascript

\node_modules\node-odata\lib\resource.js:120

      this._hooks[this._currentMethod].auth = fn;
                                            ^
TypeError: Cannot set property 'auth' of undefined

```

然后我将该120行的代码换成，`hook(this, 'auth', fn);`启动正常。这是为什么呢？

**Comment by TossShinHwa** [comment]
应该是 `all().auth()`, 详见[这里](http://tossshinhwa.github.io/node-odata/cn/#51-resource)

**Comment by fungwan** [comment]
@TossShinHwa 不好意思，是我手误。代码里面我确实是写成的`all().auth()`，只是这里我提问的时候写成了all.auth();所以，问题的本质还是存在的。依然会出上述异常。

**Comment by TossShinHwa** [comment]
看起来您使用的不是最新的版本? 麻烦更新到最新版本再试试呢.

**Comment by TossShinHwa** [comment]
测试了一下, 最新版本应该是没有问题的.
