### ISSUE TITLE
Hosting on same port as the app

### ISSUE THREAD

**Issue by lelong37** [TossShinHwa/node-odata#60]
Is there anyway to have node-odata use the same port as the app is on, or have an api to where we can pass the a current app (express) into the pipeline so that the app and the node-odata are on the same port? If needed give me a few pointers, and I can try to issue a pull request attempt for this.

**Comment by TossShinHwa** [comment]
In current version, you can't pass yourself `express` instance into `node-odata`.

But you can use [server._app](https://github.com/TossShinHwa/node-odata/blob/master/src/server.js#L11) to access `express` instance.

remember: it's a internal API, maybe it will be remove in the future. (for example: when upgrade to koa)

**Comment by TossShinHwa** [comment]
Hi @lelong37, will you make a pull request about generate `$metadata` feature for this project?

**Comment by lelong37** [comment]
Thanks we figured it out how to host on the same port.

app.ts
`
import express = require("express");
import http = require("http");
import path = require("path");
import {Config} from "./server/config/odata"
import morgan = require('morgan');

var odata = require("node-odata");
var odataServer = new Config.Odata();
var app = odataServer.init();

app.use(morgan('combined'));
app.set("port", process.env.PORT || 3000);
app.use("/", express.static(__dirname + "/public"))
app.get("/", (req, res) => {
    res.sendFile(path.join(__dirname + "/public/index.html"));
});

app.listen(app.get("port"));
`
odata.ts
`
var odata = require("node-odata");

export namespace Config {

    export class Odata {
        constructor() {

        }

        init() {
            var mongoUri = "mongodb://stations360:stations360@ds036789.mlab.com:36789/stations360";
            var odataServer = odata(mongoUri, "odata"); //todo: move into config

            odataServer.resource("applications", {
                id: String,
                name: String,
                version: String,
                description: String,
                author: String,
                menu: {
                    group: String,
                    app: String,
                    baseUrl: String,
                    actions: []
                }
            })
            
            return odataServer;
        }
    }
}
`

**Comment by TossShinHwa** [comment]
I guess you want this [exapmle](https://github.com/TossShinHwa/CMS/blob/v1.5.0/server/src/index.js#L26-L33).

`server` just like `app` which is `Express` instance. You can use `server.use` [same as](https://github.com/TossShinHwa/node-odata/blob/master/src/server.js#L109-L115) `app.use`.
