### ISSUE TITLE
求指导：  indexof ， contains 函数正确的调用格式

### ISSUE THREAD

**Issue by weitangtang** [TossShinHwa/node-odata#67]
我尝试使用如下格式 ，，返回entity is not defined  
http://localhost:8613/projectinfo?$filter=indexof(dep,'abc')

正确的调用格式该如何？

**Comment by TossShinHwa** [comment]
在使用`indexof` 函数的时候其自身只会返回一个 int,  所以需要给定一个比较的值. 比如 

```
indexof(description,'.NET') gt 0
```

了解更多请参考[这里](http://tossshinhwa.github.io/node-odata/cn/#41-filter)

**Comment by weitangtang** [comment]
帮忙写一个正确调用的链接呗，文档看了很多遍，就是没弄明白才来请教的  ：）

1. 正确的格式？  http://localhost:8613/projectinfo?$filter=indexof(dep,'abc') gt 0
             indexof(description,'.NET') gt 0
 
1.1.  description 相当于 mongodb 中的列名？？？

server.resource('projectinfo',{
    pname :String,//项目名称
    pdate:Date,//项目日期
    address:String,//项目地址
    name:String,
    tel:String,
    dep:String,//单位
    opdate:Date,
    signstatus:String,//签到状态
    signcount:Number,//签到人数
    sendstatus:String //发送状态
})

2. 另外  npm官方包里有说支持contains，但是文档里木有啊，
   请直接给个实例呗，文档太简洁了，小白很吃力哦

**Comment by TossShinHwa** [comment]
看起来你的使用时没问题的, 应该可以正常访问. 具体使用可以参考[这个示例](https://github.com/TossShinHwa/node-odata/blob/master/test/odata.query.filter.functions.test.js).

**Comment by TossShinHwa** [comment]
添加了 contains 的[相关文档](http://tossshinhwa.github.io/node-odata/cn/#41-filter).
