### ISSUE TITLE
Typings and integration with Express

### ISSUE THREAD

**Issue by OlteanuRadu** [TossShinHwa/node-odata#71]
Hello,

1) Are there any declaration files for the current version of the lib ? 
2) Considering that I'm using express generic routing for CRUD (please have a look here : https://github.com/OlteanuRadu/Nova/blob/master/src/core/webApi/webApiBaseService.ts) is there any easy way to integrate it with odata?

**Comment by TossShinHwa** [comment]
Hi @OlteanuRadu,

1) newest version is written in [README](https://github.com/TossShinHwa/node-odata/blob/master/README.md).
2) you can use [OData Function](http://tossshinhwa.github.io/node-odata/en/#52-function) to implement it, it's almost same as router.
