### ISSUE TITLE
node-odata cen't find item by id

### ISSUE THREAD

**Issue by johnsmith9264** [TossShinHwa/node-odata#73]
**Collection name:**
contacts

**node-odata version:**
0.7.15

**data in mongodb:**
{ "_id" : ObjectId("583dbc81c0f7be15f8d2fbbd"), "firstName" : "John", "lastName" : "Tolkien", "email" : "tolkien@inklings.com", "phoneNumber" : "867-5309" }
{ "_id" : ObjectId("583dbc81c0f7be15f8d2fbbe"), "firstName" : "Clive", "lastName" : "Lewis", "email" : "lewis@inklings.com", "phoneNumber" : "867-5309" }
{ "_id" : ObjectId("583dbc81c0f7be15f8d2fbbf"), "firstName" : "Owen", "lastName" : "Barfield", "email" : "barfield@inklings.com", "phoneNumber" : "867-5309" }
{ "_id" : ObjectId("583dbc81c0f7be15f8d2fbc0"), "firstName" : "Charles", "lastName" : "Williams", "email" : "williams@inklings.com", "phoneNumber" : "867-5309" }
{ "_id" : ObjectId("583dbc81c0f7be15f8d2fbc1"), "firstName" : "Roger", "lastName" : "Green", "email" : "green@inklings.com", "phoneNumber" : "867-5309" }

**code:**
const contactSchema = {
  firstName: String,
  lastName: String,
  email: String,
  phoneNumber: String
};

odataServer.resource('contacts', contactSchema);

**Search query:**
http://localhost:3000/odata/contacts(583dbc81c0f7be15f8d2fbbd)
**answer:** Not found

**Comment by TossShinHwa** [comment]
You should use `node-odata` to insert data because it will generate a id for item. It can't find it if the data insert without by `node-odata`.

read https://github.com/TossShinHwa/node-odata/issues/53 to know more.

**Comment by johnsmith9264** [comment]
Thanks! It works :)
Resolution: do not add "id" or "_id" to schema, do not insert data directly
