### ISSUE TITLE
it's not possible to filter by id

### ISSUE THREAD

**Issue by andriy-f** [TossShinHwa/node-odata#74]
it's not possible to filter by id, i.e.: `http://host/books?$filter=id eq '<existing id>'` doesn't work.
But `http://host/books?$filter=_id eq '<existing id>'` works!

**Comment by TossShinHwa** [comment]
Correct, this is a known issue.

Generally, `id` will not as the query content in $filter because you can direct query use `http://host/books(<existing id>)`.

Thank you for report this issue, I will fix it when I'm free.
