### ISSUE TITLE
How to use this with existing express instance?

### ISSUE THREAD

**Issue by smaheshw** [TossShinHwa/node-odata#83]
I want to use router object of node-odata and attach the endpoints to an existing router of express. Is it possible to do?
Example : 

const express = require('express');
const router = express.Router();

const odata = require('node-odata');
const server = odata(dbUrl);
server.resource('/books',{type: String, name: String});

const odataRouter = .... server. ???

router.use('/odata-routes', odataRouter);

module.exports = router;

**Comment by TossShinHwa** [comment]
Hi @smaheshw 

You can use odata instance same as express's.

lelong37 provide one implementation.

Reference: https://github.com/TossShinHwa/node-odata/issues/60
