### ISSUE TITLE
Skipping saving to db inside the post/put().before

### ISSUE THREAD

**Issue by pavelseverov** [TossShinHwa/node-odata#85]
Hi,

Thanks for nice software!

Is it possible to skip saving data to db inside the  **post().before** and **put().before** ?
Or can you suggest alternative solution?
I need to validate data and not to save it to db in case it is invalid (keeping other functionality in place).

```
server.resource('book',{…}).post().before(function (entity) {
  //validate entity here, and skip saving it to db if something is wrong 
})
```
Thank you!

**Comment by TossShinHwa** [comment]
Hi @pavelseverov 

Sadly, you cant `return false` to skip saving resource in `before` pipe, `before` was designed to format the data , so it was not considered to be used to refuse to save.

There is a ugly way to do this. It's will be skip if you throw an Error in `before` pipe. like this:

```
server.resource('book',{…}).post().before(function (entity) {
  //validate entity here, and skip saving it to db if something is wrong 
  if (isInvalid) {
    throw new Error('Error entity');
  }
})
```

It will be return `500 Error entity` and skip saving, this is not a correct status code (correct should be 422), just work.

I will try to support `return false` to skip saving in `before` pipe ASAP.

Thank you.

**Comment by TossShinHwa** [comment]
UPDATE:

use `http-errors` module will be resolve this issue.

```
var { HttpError } = require('http-errors');

server.resource('book',{…}).post().before(function (entity) {
  //validate entity here, and skip saving it to db if something is wrong 
  if (isInvalid) {
    throw createError.UnprocessableEntity();
  }
})
```

**Comment by pavelseverov** [comment]
@TossShinHwa, thank you very much for quick response! :-)
Your suggestion is working well. But it rejects not only saving to db, but returned post result as well.
It will be good to have possibility to skip only saving, but keep other functionality in place.

**Comment by TossShinHwa** [comment]
@pavelseverov, why should post result as well even if it skipped saving? I think the client should know it's failed to save.

**Comment by pavelseverov** [comment]
> client should know it's failed to save.
...and probably some other details (the reasons of failing validations, etc), which is good to deliver inside the json object back to client.
Though, personally, this "skip saving" is not actual for me already. Thanks for you replies, anyway!

**Comment by TossShinHwa** [comment]
> the reasons of failing validations

If you want to return some message to client, `http-error` support add a content, it will be return to client with body. For example:

```js
var createError = require('http-errors');

server.resource('book',{…}).post().before(function (entity) {
  //validate entity here, and skip saving it to db if something is wrong 
  if (isInvalid) {
    throw createError.UnprocessableEntity({
      error: [{
        field: 'name',
        reason: 'name maxlength is 20',
      }, {
        field: 'age',
        reason: 'age must be rangeof 1 to 120',
      }]
    });
  }
})
```


```shell
$curl -X POST --data "data=xxx" http://localhost:3000/books -i

HTTP/1.1 422 Unprocessable Entity
Vary: X-HTTP-Method-Override
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 116
ETag: W/"74-gNJRiLVGcjeOGAoIa4D8xeNflXU"
Date: Fri, 19 May 2017 02:05:15 GMT
Connection: keep-alive

{"error":[{"field":"name","reason":"name maxlength is 20"},{"field":"age","reason":"age must be rangeof 1 to 120"}]}
```

**Comment by pavelseverov** [comment]
@TossShinHwa, thank you very much for your suggestions!
