### ISSUE TITLE
asynchronous calls inside the post/put().before

### ISSUE THREAD

**Issue by pavelseverov** [TossShinHwa/node-odata#86]
Hi!

Is it possible to make something asynchronous inside **post().before** and **put().before**, and then format the data accordingly?
For example I need to make searching in mongodb and then update returned **entity**.
Code below works Ok, with one exception – returned **entity.found** is not updated.
Thanks for your suggestions!

```
        server.resource('requests', {...}).post().before(function (entity) {
            server._db.collection('products').find({"article":entity.article}).toArray(function (err, docs) {
                entity.found="found articles"+docs.length
            })
        })
```

**Comment by TossShinHwa** [comment]
Hi @pavelseverov ,

Interesting, I think Restful API should be a pure operation, without magic and predictable. In my options, I will try to split this opera to two request.

One for request to get `products` length, One for update `requests` with updated entity. This has some impact on performance, but I think it is acceptable. This will be clearer and more predictable.

On the other hand, `before` hook not support a asynchronous function for now. [Here](https://github.com/TossShinHwa/node-odata/issues/81) has a way to make a asynchronous function.

**Comment by pavelseverov** [comment]
Hi @TossShinHwa, 

Thanks for your suggestions! Using of Express middleware solves my problem.
