### ISSUE TITLE
JSON Patch support for partial updates on resource

### ISSUE THREAD

**Issue by ferquo** [TossShinHwa/node-odata#91]
For an endpoint to be RESTful, it should support partial updates with the PATCH attribute.
The best way to achieve this is using JSON Patch (http://jsonpatch.com/) (https://tools.ietf.org/html/rfc6902)

**Comment by TossShinHwa** [comment]
We should directly update partial entity abide by [OData Protocol](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793719).
